apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: "true"
    #apps.tanzu.vmware.com/language: java
spec:
  params:
    - name: gitImplementation
      value: libgit2
  source:
    git:
      url: https://dev.azure.com/gorkemozlu-tanzu/tap/_git/tap
      ref:
        branch: main