apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-steeltoe
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-steeltoe
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: weatherforecast-steeltoe
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: nugetconfig
  source:
    git:
      url: https://git.tmc.h2o-4-10367.h2o.vmware.com/tanzu/weather-dotnet.git
      ref:
        branch: main
#https://github.com/gorkemozlu/weatherforecast-steeltoe-net-tap