#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: v1
data:
  password: #@ base64.encode(data.values.image_registry_password)
  username: #@ base64.encode(data.values.image_registry_user)
kind: Secret
metadata:
  creationTimestamp: null
  name: chart-pull
  namespace: default
---
apiVersion: v1
data:
  .dockerconfigjson: #@ base64.encode(json.encode({"auths":{data.values.image_registry:{"username":data.values.image_registry_user,"password":data.values.image_registry_password,"auth":base64.encode("{}:{}".format(data.values.image_registry_user,data.values.image_registry_password))}}}))
kind: Secret
metadata:
  creationTimestamp: null
  name: container-pull
  namespace: default
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
data:
  ca-bundle: #@ data.values.ca_cert_data
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ca-bundle-config
  namespace: crossplane-system