tap_install:
  values:
    shared:
      ingress_domain: tap.mytanzu.org
      image_registry:
        project_path: harbor.mgt.mytanzu.org/tap-15
    ceip_policy_disclosed: true
    profile: full
    supply_chain: basic
    ootb_supply_chain_basic:
      registry:
        server: harbor.mgt.mytanzu.org
        repository: tap-15/supplychain
      gitops:
        ssh_secret: "git-secret"
      maven:
        repository:
          url: https://nexus-80.tmc.h2o-4-10367.h2o.vmware.com/repository/maven-central/
          secret_name: "maven-credentials"
    ootb_supply_chain_testing:
      registry:
        server: harbor.mgt.mytanzu.org
        repository: tap-15/supplychain
      gitops:
        ssh_secret: "git-secret"
      maven:
        repository:
          url: https://nexus-80.tmc.h2o-4-10367.h2o.vmware.com/repository/maven-central/
          secret_name: "maven-credentials"
    ootb_supply_chain_testing_scanning:
      registry:
        server: harbor.mgt.mytanzu.org
        repository: tap-15/supplychain
      gitops:
        ssh_secret: "git-secret"
      maven:
        repository:
          url: https://nexus-80.tmc.h2o-4-10367.h2o.vmware.com/repository/maven-central/
          secret_name: "maven-credentials"
    contour:
      envoy:
        service:
          type: LoadBalancer
    buildservice:
      kp_default_repository: harbor.mgt.mytanzu.org/tap-15/build
      kp_default_repository_username: admin
    tap_gui:
      service_type: ClusterIP
      metadataStoreAutoconfiguration: true
      ingressEnabled: "true"
      app_config:
        catalog:
          locations:
          - type: url
            target: https://github.com/MoSehsah/bank-demo/blob/main/catalog/catalog-info.yaml
    cnrs:
      domain_template: '{{.Name}}-{{.Namespace}}.{{.Domain}}'
    metadata_store:
      ns_for_export_app_cert: '*'
      app_service_type: ClusterIP
    scanning:
      metadataStore:
        url: ""
    grype:
      namespace: my-apps
      targetImagePullSecret: registry-credentials
      db:
        dbUpdateUrl: https://minio.tmc.h2o-4-10367.h2o.vmware.com/grype/databases/listing.json
    policy:
      tuf_enabled: false
    tap_telemetry:
      installed_for_vmware_internal_use: "true"
    namespace_provisioner:
      controller: false
      gitops_install:
        ref: origin/main
        subPath: gorkem/namespace-provisioner/namespaces
        url: https://github.com/gorkemozlu/tap-gitops-ri.git
      additional_sources:
      - git:
          ref: origin/main
          subPath: gorkem/namespace-provisioner/resources
          url: https://github.com/gorkemozlu/tap-gitops-ri.git
        path: _ytt_lib/resources
      import_data_values_secrets:
      - name: workload-git-auth
        namespace: tap-install
        create_export: true